1) Read any CSV data file from google colab and create a dataframe using padas. a) Next find the mean value of each column. b) Find indices where nan (no value or value missing) value is present. c) Replace the missing value using the mean value.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
car_sales = pd.read_csv("/content/car-sales-extended-missing-data.csv")
car_sales

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [5]:
x = np.mean(car_sales["Odometer (KM)"])
x

131253.23789473684

In [6]:
y = np.mean(car_sales["Doors"])
y

4.011578947368421

In [7]:
z = np.mean(car_sales["Price"])
z

16042.814736842105

In [8]:
car_sales.isnull().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [10]:
car_sales.fillna(np.mean(car_sales["Odometer (KM)"]),inplace=True)

In [11]:
car_sales.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

2) Imagine, you are given a list of items in a DataFrame as below. D = [‘A’,’B’,’C’,’D’,’E’,’AA’,’AB’], Now convert and display this categorical data using 1) dummies function of pandas and 2) level encoder function of Scikitlearn.

In [12]:
# Create dataframe
df = pd.DataFrame({'D': ["A","B","C","D","E","AA","AB"],
'B': [10,20,30,40,50,60,70]}, index=[0,1,2,3,4,5,6])
print(df)
# using get_dummies function of pandas package
df_dummies= pd.get_dummies(df, prefix='A', 
columns=['D'])
print(df_dummies)

    D   B
0   A  10
1   B  20
2   C  30
3   D  40
4   E  50
5  AA  60
6  AB  70
    B  A_A  A_AA  A_AB  A_B  A_C  A_D  A_E
0  10    1     0     0    0    0    0    0
1  20    0     0     0    1    0    0    0
2  30    0     0     0    0    1    0    0
3  40    0     0     0    0    0    1    0
4  50    0     0     0    0    0    0    1
5  60    0     1     0    0    0    0    0
6  70    0     0     1    0    0    0    0


In [13]:
# Alternatively you can use sklearn package's LabelEncoder function
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['A_AB'] = le.fit_transform(df.D)
print(df)

    D   B  A_AB
0   A  10     0
1   B  20     3
2   C  30     4
3   D  40     5
4   E  50     6
5  AA  60     1
6  AB  70     2


3) Read a CSV datafile using pandas dataframe then apply 1) min-max normalization and 2) z-score normalization over the each column of the dataset.

In [14]:
from sklearn import datasets
from sklearn import preprocessing
# Load dataset from sklearn dataset package
iris_ = datasets.load_iris()
# seperate input and target features
X = iris_.data
y = iris_.target
print(X)
#Min-max normalization
minmax_scale = preprocessing.MinMaxScaler().fit(X)
X_minmax = minmax_scale.transform(X)
print(X_minmax)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

4) Read a CSV datafile using pandas dataframe then find the covariance and correlation.

In [15]:
# for showing the coviariance
iris = pd.read_csv("/content/iris.csv")
iris

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [16]:
iris.cov()

sepal.length  sepal.width  petal.length  petal.width
sepal.length      0.685694    -0.042434      1.274315     0.516271
sepal.width      -0.042434     0.189979     -0.329656    -0.121639
petal.length      1.274315    -0.329656      3.116278     1.295609
petal.width       0.516271    -0.121639      1.295609     0.581006

In [17]:
iris.corr()

sepal.length  sepal.width  petal.length  petal.width
sepal.length      1.000000    -0.117570      0.871754     0.817941
sepal.width      -0.117570     1.000000     -0.428440    -0.366126
petal.length      0.871754    -0.428440      1.000000     0.962865
petal.width       0.817941    -0.366126      0.962865     1.000000